name: CI/CD
on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

env:
  PROJECT_ID: voltaic-country-280607
  GCP_SA: bivuanem@voltaic-country-280607.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set env vars (dev)
        if: endsWith(github.ref, '/dev')
        run: |
          echo "FUNCTION_NAME=vuanem-ecommerce-service-dev" >> $GITHUB_ENV
          echo "PUBLIC_URL=https://us-central1-voltaic-country-280607.cloudfunctions.net/vuanem-ecommerce-service-dev" >> $GITHUB_ENV
          echo "CHAT_ID=-645664226" >> $GITHUB_ENV

      - name: Set env vars (prod)
        if: endsWith(github.ref, '/master')
        run: |
          echo "FUNCTION_NAME=vuanem-ecommerce-service" >> $GITHUB_ENV
          echo "PUBLIC_URL=https://us-central1-voltaic-country-280607.cloudfunctions.net/vuanem-ecommerce-service" >> $GITHUB_ENV
          echo "CHAT_ID=-1001685563275" >> $GITHUB_ENV

      - name: Deploy to Cloud Functions
        run: >-
          gcloud functions deploy ${{ env.FUNCTION_NAME }}
          --allow-unauthenticated
          --entry-point=main
          --region=us-central1
          --timeout=530
          --project=${{ env.PROJECT_ID }}
          --memory=4096MB
          --runtime=python39
          --trigger-http
          --service-account=${{ env.GCP_SA }}
          --set-env-vars=GCP_SA=${{ env.GCP_SA }},PUBLIC_URL=${{ env.PUBLIC_URL}},CONSUMER_KEY=${{ secrets.CONSUMER_KEY }},CONSUMER_SECRET=${{ secrets.CONSUMER_SECRET }},ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }},TOKEN_SECRET=${{ secrets.TOKEN_SECRET }},ACCOUNT_ID=${{ secrets.ACCOUNT_ID }},TIKI_ACCESS_TOKEN=${{ secrets.TIKI_ACCESS_TOKEN }},TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
