name: CI/CD

on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

concurrency: ${{ github.ref }}

env:
  PROJECT_ID: voltaic-country-280607
  GCP_SA: bivuanem@voltaic-country-280607.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set env vars (dev)
        if: endsWith(github.ref, '/dev')
        run: |
          echo "FUNCTION_NAME=vuanem-ecommerce-service-dev" >> $GITHUB_ENV
          echo "PYTHON_ENV=dev" >> $GITHUB_ENV
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN_DEV }}" >> $GITHUB_ENV

      - name: Set env vars (prod)
        if: endsWith(github.ref, '/master')
        run: |
          echo "FUNCTION_NAME=vuanem-ecommerce-service" >> $GITHUB_ENV
          echo "PYTHON_ENV=prod" >> $GITHUB_ENV
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> $GITHUB_ENV

      - name: Auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Deploy
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: ${{ env.FUNCTION_NAME }}
          entry_point: main
          runtime: python39
          memory_mb: 2048MB,
          timeout: 530,
          service_account_email: ${{ env.GCP_SA }}
          env_vars: PYTHON_ENV=${{ env.PYTHON_ENV }},CONSUMER_KEY=${{ secrets.CONSUMER_KEY }},CONSUMER_SECRET=${{ secrets.CONSUMER_SECRET }},ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }},TOKEN_SECRET=${{ secrets.TOKEN_SECRET }},ACCOUNT_ID=${{ secrets.ACCOUNT_ID }},TIKI_CLIENT_SECRET=${{ secrets.TIKI_CLIENT_SECRET }},LAZ_APP_SECRET=${{ secrets.LAZ_APP_SECRET }},SHOPEE_API_KEY=${{ secrets.SHOPEE_API_KEY }},TELEGRAM_TOKEN=${{ env.TELEGRAM_TOKEN }},SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
